# Site settings
title: Coding Time
email: coding-time@xiphe.net
description: Coding and stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coding-time.github.io/" # the base hostname & protocol for your site
github_username: Coding-Time

# Build settings
markdown: kramdown
